const char *preset_menu =
    "serial --unit=0 --speed=115200\n"
    "terminal --timeout=0 --dumb console\n"
    "rootnoverify (hd0,0)\n"
    "default 2\n"
    "fallback 1 0\n"
    "timeout 3\n"
    "\n"
    "title sysloader\n"
    "cmdline (hd0,0)/cmdline\n"
    "kernel --use-cmd-line (hd0,0)/kernel\n"
    "initrd (hd0,0)/ramdisk\n"
    "\n"
    "title recovery\n"
    "cmdline (hd0,1)/cmdline\n"
    "kernel --use-cmd-line (hd0,1)/kernel\n"
    "initrd (hd0,1)/ramdisk\n"
    "\n"
    "title std_boot\n"
    "cmdline (hd0,2)/cmdline\n"
    "kernel --use-cmd-line (hd0,2)/kernel\n"
    "initrd (hd0,2)/ramdisk\n";
